-- ==============================================
-- Agent Runtime: 事件闭环（事件事实 / Incident / 证据 / 决策）
-- 设计见 docs/agent/ops-agent-design.md §5.1 / §6
-- ==============================================

-- 事件事实表（收敛：fingerprint 归并 + 拓扑抑制）
CREATE TABLE IF NOT EXISTS agent_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT,
    cluster_id BIGINT NOT NULL,
    fingerprint TEXT NOT NULL,
    kind VARCHAR(30) NOT NULL,
    severity VARCHAR(10) NOT NULL,
    object_type VARCHAR(20),
    object_id VARCHAR(128),
    title TEXT NOT NULL,
    summary TEXT,
    metrics_json TEXT,
    state VARCHAR(12) NOT NULL DEFAULT 'open',
    occurrence_count BIGINT NOT NULL DEFAULT 1,
    suppressed_by BIGINT,
    first_seen_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_seen_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (cluster_id) REFERENCES clusters(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_agent_events_scope ON agent_events(cluster_id, state, last_seen_at);
CREATE INDEX IF NOT EXISTS idx_agent_events_fp ON agent_events(fingerprint, state);

-- Incident 聚合根（复开：resolved 30 天内同 dedupe_key 重新 open）
CREATE TABLE IF NOT EXISTS agent_incidents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT,
    cluster_id BIGINT NOT NULL,
    dedupe_key TEXT NOT NULL,
    title TEXT NOT NULL,
    impact_summary TEXT,
    status VARCHAR(14) NOT NULL DEFAULT 'open',
    input_digest TEXT,
    output_json TEXT,
    llm_provider TEXT,
    llm_model TEXT,
    llm_tokens BIGINT,
    duration_ms BIGINT,
    error TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    resolved_at TIMESTAMP,
    FOREIGN KEY (cluster_id) REFERENCES clusters(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_agent_incidents_scope ON agent_incidents(cluster_id, status, created_at);
CREATE INDEX IF NOT EXISTS idx_agent_incidents_dedupe ON agent_incidents(dedupe_key, status);

-- Incident ↔ 事件 关联
CREATE TABLE IF NOT EXISTS agent_incident_events (
    incident_id BIGINT NOT NULL,
    event_id BIGINT NOT NULL,
    FOREIGN KEY (incident_id) REFERENCES agent_incidents(id) ON DELETE CASCADE,
    FOREIGN KEY (event_id) REFERENCES agent_events(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_aie_incident ON agent_incident_events(incident_id);

-- 证据（固定取证流水线各阶段产物；quality: strong/weak）
CREATE TABLE IF NOT EXISTS agent_evidences (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    incident_id BIGINT NOT NULL,
    stage VARCHAR(20) NOT NULL,
    collector VARCHAR(30) NOT NULL,
    payload_json TEXT NOT NULL,
    quality VARCHAR(10) NOT NULL DEFAULT 'strong',
    error TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (incident_id) REFERENCES agent_incidents(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_agent_evidences_incident ON agent_evidences(incident_id, stage);

-- 决策审计（每阶段一条：intake / evidence / rule_diagnosis / llm_hypothesis）
CREATE TABLE IF NOT EXISTS agent_decisions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    incident_id BIGINT NOT NULL,
    stage VARCHAR(30) NOT NULL,
    status VARCHAR(12) NOT NULL DEFAULT 'completed',
    input_json TEXT,
    output_json TEXT,
    llm_provider TEXT,
    llm_model TEXT,
    llm_tokens BIGINT,
    error TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (incident_id) REFERENCES agent_incidents(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_agent_decisions_incident ON agent_decisions(incident_id, stage);
